version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: postgres
    restart: always
